version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    commit-message:
      prefix: (build)-deps
      include: scope
    pull-request-branch-name:
      separator: '-'
